services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  zitadel:
    user: '${ZITADEL_DEV_UID}'
    image: '${ZITADEL_IMAGE:-ghcr.io/zitadel/zitadel:v2.71.6}'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled --config /zitadel.yaml --steps /zitadel.yaml'
    ports:
      - "8080:8080"
    volumes:
      - ./keys:/keys
      - ./zitadel.yaml:/zitadel.yaml
    healthcheck:
      test: ['CMD', '/app/zitadel', 'ready', "--config", "/zitadel.yaml"]
      interval: '2s'
      timeout: '30s'
      retries: 60
    depends_on:
      db:
        condition: 'service_healthy'

  setup:
    user: '${ZITADEL_DEV_UID}'
    container_name: setup
    build: .
    environment:
      KEYS_DIRECTORY: /keys
      SERVICE: http://zitadel:8080
    volumes:
      - "./keys:/keys"
    depends_on:
      zitadel:
        condition: 'service_healthy'
