name: Test Provider

on: pull_request

jobs:

  lint:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Avoid Typecheck Error On Embedded Fields
        run: |
          touch acceptance/keys/instance-level-admin-sa.json
          touch acceptance/keys/org-level-admin-sa.json

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          github-token: ${{ github.token }}
          only-new-issues: true
          skip-pkg-cache: true
          skip-build-cache: true

  test:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Make Machinekey Directory Writable
      working-directory: acceptance
      run: "chmod -R 777 keys"

    - name: Setup ZITADEL
      working-directory: acceptance
      run: docker compose run setup

    - name: Download Go Modules
      run: go mod download

    - name: Run Acceptance Tests
      run: TF_ACC=1 go test -coverprofile=profile.cov ./...

    - name: Publish Coverage
      uses: codecov/codecov-action@v3.1.4
      with:
        file: profile.cov
        name: acceptance-tests
        flags: acceptance-tests

    - name: Save Docker Compose Logs
      if: always()
      working-directory: acceptance
      run: docker compose logs > .docker-compose.log

    - name: Archive Docker Compose Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pull-request-tests
        path: |
          acceptance/.docker-compose.log
        retention-days: 30
